FROM golang:1.11-stretch

RUN apt-get install git

ADD https://github.com/golang/dep/releases/download/v0.5.0/dep-linux-amd64 /usr/bin/dep
RUN chmod +x /usr/bin/dep

WORKDIR $GOPATH/src/github.com/joatmon08/hello
COPY Gopkg.toml Gopkg.lock ./
RUN dep ensure --vendor-only

COPY . ./

CMD go test -v github.com/joatmon08/hello/test/integration
