FROM golang:1.15-stretch

RUN apt-get install git

ADD https://github.com/golang/dep/releases/download/v0.5.0/dep-linux-amd64 /usr/bin/dep
RUN chmod +x /usr/bin/dep

WORKDIR /app

COPY go.mod go.sum ./

RUN go mod download

COPY . .

CMD go test -v github.com/joatmon08/hello/test/integration
