---
apiVersion: apps/v1beta2
kind: Deployment
metadata:
  name: helloworld
  labels:
    app: helloworld
spec:
  replicas: 1
  selector:
    matchLabels:
      app: helloworld
  template:
    metadata:
      labels:
        app: helloworld
    spec:
      securityContext:
        runAsUser: 1000
        fsGroup: 2000
      containers:
      - name: helloworld
        image: joatmon08/hello:latest
        imagePullPolicy: Always
        ports:
        - containerPort: 8001
          name: http
          protocol: TCP
        - containerPort: 8002
          name: metrics
          protocol: TCP
        securityContext:
          allowPrivilegeEscalation: false
---
apiVersion: v1
kind: Service
metadata:
  name: helloworld
  labels:
    app: helloworld
spec:
  ports:
  - name: http
    protocol: TCP
    port: 80
    targetPort: 8001
  selector:
    app: helloworld
