---
version: 2

defaults: &defaults
  docker:
    - image: circleci/golang:1.11
  working_directory: /go/src/github.com/joatmon08/hello
  environment:
    LIBRARY: joatmon08
    CONTAINER_NAME: hello

jobs:
  test:
    <<: *defaults
    steps:
      - checkout
      - run:
          name: Install dependencies
          command: dep ensure
      - run:
          name: Test application
          command: go test github.com/joatmon08/hello

  build:
    <<: *defaults
    steps:
      - checkout
      - setup_remote_docker
      - run:
          name: Install dependencies
          command: dep ensure
      - run:
          name: Build container
          command: |
            echo $DOCKER_HUB_KEY | docker login -u $DOCKER_HUB_USER --password-stdin
            GOOS=linux GOARCH=amd64 go build main.go
            docker build -t joatmon08/hello:latest .
            docker tag $LIBRARY/$CONTAINER_NAME:latest $LIBRARY/$CONTAINER_NAME:$CIRCLE_BUILD_NUM-$CIRCLE_SHA1
            docker push $LIBRARY/$CONTAINER_NAME:$CIRCLE_BUILD_NUM-$CIRCLE_SHA1
            docker push $LIBRARY/$CONTAINER_NAME:latest

workflows:
  version: 2
  hello:
    jobs:
      - test
      - build:
          requires:
            - test