---
version: 2

defaults: &defaults
  docker:
    - image: circleci/golang:1.11
  working_directory: /go/src/github.com/joatmon08/hello
  environment:
    LIBRARY: joatmon08
    CONTAINER_NAME: hello

jobs:
  test:
    <<: *defaults
    steps:
      - checkout
      - run:
          name: Install dependencies
          command: dep ensure
      - run:
          name: Test application
          command: go test github.com/joatmon08/hello/test/unit

  build:
    <<: *defaults
    steps:
      - checkout
      - setup_remote_docker
      - run:
          name: Install dependencies
          command: dep ensure
      - run:
          name: Build application container
          command: |
            echo $DOCKER_HUB_KEY | docker login -u $DOCKER_HUB_USER --password-stdin
            CGO_ENABLED=0 GOOS=linux go build -a -installsuffix cgo -o main .
            docker build -t joatmon08/hello:latest .
            docker tag $LIBRARY/$CONTAINER_NAME:latest $LIBRARY/$CONTAINER_NAME:$CIRCLE_BUILD_NUM-$CIRCLE_SHA1
            docker push $LIBRARY/$CONTAINER_NAME:$CIRCLE_BUILD_NUM-$CIRCLE_SHA1
            docker push $LIBRARY/$CONTAINER_NAME:latest
      - run:
          name: Build integration test container
          command: |
            docker build -t joatmon08/hello:integration-tests -f Dockerfile.test .
            docker tag $LIBRARY/$CONTAINER_NAME:integration-tests $LIBRARY/$CONTAINER_NAME:integration-tests-$CIRCLE_BUILD_NUM-$CIRCLE_SHA1
            docker push $LIBRARY/$CONTAINER_NAME:integration-tests-$CIRCLE_BUILD_NUM-$CIRCLE_SHA1
            docker push $LIBRARY/$CONTAINER_NAME:integration-tests

workflows:
  version: 2
  hello:
    jobs:
      - test
      - build:
          requires:
            - test