---
version: 2.1

orbs:
  vulnerability-checker: whitesource/vulnerability-checker@19.9.2

defaults: &defaults
  docker:
    - image: circleci/golang:1.12
  environment:
    LIBRARY: joatmon08
    CONTAINER_NAME: hello

jobs:
  test:
    <<: *defaults
    steps:
      - checkout
      - run:
          name: Test application
          command: |
            go test -tags unit ./...

  build:
    <<: *defaults
    steps:
      - checkout
      - setup_remote_docker
      - run:
          name: Build application container
          command: |
            echo $DOCKER_HUB_KEY | docker login -u $DOCKER_HUB_USER --password-stdin
            CGO_ENABLED=0 GOOS=linux go build -a -installsuffix cgo -o hello .
            docker build -t $LIBRARY/$CONTAINER_NAME:latest .
            docker tag $LIBRARY/$CONTAINER_NAME:latest $LIBRARY/$CONTAINER_NAME:$CIRCLE_BUILD_NUM-$CIRCLE_SHA1
            docker push $LIBRARY/$CONTAINER_NAME:$CIRCLE_BUILD_NUM-$CIRCLE_SHA1
            docker push $LIBRARY/$CONTAINER_NAME:latest
      - run:
          name: Build integration test container
          command: |
            docker build -t joatmon08/hello:integration-tests -f Dockerfile.test .
            docker tag $LIBRARY/$CONTAINER_NAME:integration-tests $LIBRARY/$CONTAINER_NAME:integration-tests-$CIRCLE_BUILD_NUM-$CIRCLE_SHA1
            docker push $LIBRARY/$CONTAINER_NAME:integration-tests-$CIRCLE_BUILD_NUM-$CIRCLE_SHA1
            docker push $LIBRARY/$CONTAINER_NAME:integration-tests
      - run:
          name: store image version
          command: |
            mkdir /tmp/build
            echo "IMAGE_VERSION=$CIRCLE_BUILD_NUM-$CIRCLE_SHA1" > /tmp/build/version.env
      - persist_to_workspace:
          name: persist version across jobs
          root: /tmp/build
          paths:
            - version.env

  security:
    <<: *defaults
    steps:
      - vulnerability-checker/scan

  production:
    <<: *defaults
    steps:
      - run:
          name: prod
          command: |
            echo "Pushed"

workflows:
  version: 2
  hello:
    jobs:
      - test
      - build:
          requires:
            - test
      - security:
          requires:
            - build
      - approver-1:
          type: approval
          requires:
            - security
      - approver-2:
          type: approval
          requires:
            - security
      - production:
          requires:
            - approver-1
            - approver-2