---
version: 2.1

orbs:
  vulnerability-checker: whitesource/vulnerability-checker@19.9.2

defaults: &defaults
  docker:
    - image: circleci/golang:1.15
      auth:
        username: joatmon08
        password: $DOCKER_HUB_KEY
  environment:
    LIBRARY: joatmon08
    CONTAINER_NAME: hello

jobs:
  test:
    <<: *defaults
    steps:
      - checkout
      - run:
          name: Test application
          command: |
            go test -tags unit ./...

  build:
    <<: *defaults
    steps:
      - checkout
      - setup_remote_docker
      - run:
          name: Build application container
          command: |
            echo $DOCKER_HUB_KEY | docker login -u $DOCKER_HUB_USER --password-stdin
            docker build --build-arg version=$CIRCLE_BUILD_NUM -t $LIBRARY/$CONTAINER_NAME:$CIRCLE_BUILD_NUM .
            docker tag $LIBRARY/$CONTAINER_NAME:$CIRCLE_BUILD_NUM $LIBRARY/$CONTAINER_NAME:latest
            docker push $LIBRARY/$CONTAINER_NAME:$CIRCLE_BUILD_NUM
            docker push $LIBRARY/$CONTAINER_NAME:latest
      - run:
          name: store image version
          command: |
            mkdir /tmp/build
            echo "IMAGE_VERSION=$CIRCLE_BUILD_NUM" > /tmp/build/version.env
      - persist_to_workspace:
          name: persist version across jobs
          root: /tmp/build
          paths:
            - version.env

  production:
    <<: *defaults
    steps:
      - run:
          name: prod
          command: |
            echo "Pushed"

workflows:
  version: 2
  hello:
    jobs:
      - test
      - build:
          requires:
            - test
      - vulnerability-checker/scan:
          requires:
            - build
      - approver-1:
          type: approval
          requires:
            - vulnerability-checker/scan
      - approver-2:
          type: approval
          requires:
            - vulnerability-checker/scan
      - production:
          requires:
            - approver-1
            - approver-2